# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f63e8dff7a727392fdb41c2d0b35f0b6c918f0ae07deb052face0aca3e77191d47d32d6e4a339951b770571f5f297d1d928f4fc8b5cf8624886779067f57ef2

test:
  secret_key_base: 7309656f6653a906c26436f3a766a28713bb5f43889078cdd479a541653be865566560b3f7e92707ec873e176cc18ff8d95bbd237ebf3d26f3a7378bac057fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
